### ISSUE TITLE
Error showing in update function

### ISSUE THREAD

**Issue by kkaajjaall** [ithqindia/metroclub#103]
http://127.0.0.1:8000/me/referee 
ArgumentCountError
Too few arguments to function App\Http\Controllers\RefereeDataController::update(), 1 passed in C:\xampp\htdocs\new-clone\metroclub\vendor\laravel\framework\src\Illuminate\Routing\Controller.php on line 54 and exactly 2 expected
http://127.0.0.1:8000/me/referee

**Comment by ithqindia** [comment]
Check app/Http/Controllers/EmploymentDataController.php too

**Comment by ithqindia** [comment]
<form class="row g-3" method="post" action="{{ $actionUrl }}">
resources/views/me/referee-form.blade.php
