### ISSUE TITLE
Is enabled form field Is not showing selected value on all forms when we edit

### ISSUE THREAD

**Issue by ithqindia** [ithqindia/metroclub#106]
On all forms add check similar to this
`<input class="form-check-input" type="checkbox" name="is_enabled" value="1" @if(isset($staff) && $staff->is_enabled) checked @endif>Is enabled?`

**Comment by ithqindia** [comment]
Once this is done add link to pull request here

**Comment by ithqindia** [comment]
**Steps to replicate**

- Create a new entry 
- Set is enabled to checked.
- Edit the same entry

**Error :** See that enabled is no checked by default

**Comment by manii283** [comment]
https://github.com/ithqindia/metroclub/pull/114
issue solved

**Comment by ithqindia** [comment]
Fixes in https://github.com/ithqindia/metroclub/pull/114
