### ISSUE TITLE
Extra score show data page wrong titles

### ISSUE THREAD

**Issue by ithqindia** [ithqindia/metroclub#108]
Most of the extra score pages have title as `<h1 class="d-flex align-items-center text-dark fw-bolder fs-3 my-1">Account Overview</h1>` change it to proper page title

**Comment by ithqindia** [comment]
Once this is done add link to pull request here

**Comment by ithqindia** [comment]
Also the date is showing in wrong format like **2022-01-15** it should be **10 January 2022**

**Comment by manii283** [comment]
issue solved

**Comment by ithqindia** [comment]
Fixes in https://github.com/ithqindia/metroclub/pull/114
