### ISSUE TITLE
Return to student page 

### ISSUE THREAD

**Issue by ithqindia** [ithqindia/metroclub#111]
When we add data to a student it redirect back to students page 
It should redirect back to the individual student page.

**Comment by ithqindia** [comment]
How to solve 
- app/Http/Controllers/AddressController.php
- `return redirect('/admin/students');`
- change this to 
- `return redirect("/admin/students/{$user->id}");`
- check all `update` and `store` function and update accordingly

**Comment by manii283** [comment]
issues solved

**Comment by ithqindia** [comment]
Fixes in https://github.com/ithqindia/metroclub/pull/114
