### ISSUE TITLE
Gmat form error 

### ISSUE THREAD

**Issue by kkaajjaall** [ithqindia/metroclub#178]
in gmat form error msg not showing propertly

**Comment by ithqindia** [comment]
![Screenshot 2022-03-30 at 12 57 30 PM](https://user-images.githubusercontent.com/93969763/160775725-28d0f37c-a407-4b00-8240-a28572351d52.png)

**Comment by ithqindia** [comment]
Fixed in https://github.com/ithqindia/metroclub/pull/179
