### ISSUE TITLE
validation error

### ISSUE THREAD

**Issue by kkaajjaall** [ithqindia/metroclub#56]
http://127.0.0.1:8000/admin/students/1/extra-score/pearson-test-english 
not taking validation

**Comment by ithqindia** [comment]
`@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif`
Add this and check if its validting

**Comment by kkaajjaall** [comment]
done
