### ISSUE TITLE
diploma form update issue

### ISSUE THREAD

**Issue by manii283** [ithqindia/metroclub#60]
http://127.0.0.1:8000/admin/students/1/diploma

not taking validation in select (status)
not taking value in update  (Year to and Status)

**Comment by ithqindia** [comment]
Year issue fixed in https://github.com/ithqindia/metroclub/pull/95
Select issue same as https://github.com/ithqindia/metroclub/issues/63

**Comment by ithqindia** [comment]
Fixed in https://github.com/ithqindia/metroclub/pull/98
