### ISSUE TITLE
Page header is missing on following pages

### ISSUE THREAD

**Issue by ithqindia** [ithqindia/metroclub#75]
This block is missing on following pages

![Screenshot 2022-01-10 at 1 54 20 PM](https://user-images.githubusercontent.com/93969763/148736318-ce19e2fb-7ad9-4455-b2aa-c7b1e2ef9c32.png)

- /me/employee
- /me/referee
- /me/personal-info
- /me/selfie - Also has wrong title

Update all text "No information available" with "Page-title information not available". Replace Page-title with name of details

**Comment by kkaajjaall** [comment]
issue resolved

**Comment by ithqindia** [comment]
Fixed in https://github.com/ithqindia/metroclub/pull/82
